#url: https://derekdileo.github.io

url: http://localhost
baseurl:

# Site settings
title: Derek DiLeo
email: derekfdileo@gmail.com
description: "Hello, I'm Derek! I'm an aspiring software engineer."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFCC00
  secondary: 806b19
  secondary-dark: 333

# Team names, titles and social links
people:
  - name: Derek DiLeo
    pic: 1
    position: Software Engineer
    social:
      - title: twitter
        url: https://twitter.com/rockwithdjdrek
      - title: linkedin
        url: https://www.linkedin.com/in/derek-dileo
      - title: github
        url: https://github.com/derekdotdev

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/rockwithdjdrek
  - title: linkedin
    url: https://www.linkedin.com/in/derek-dileo
  - title: github
    url: https://github.com/derekdotdev

# Postal address (add as many lines as necessary)
address:
  - line: 5924 Orsino Ln
  - line: Cocoa, FL 32926

# Build settings
markdown: kramdown
permalink: pretty
